PEAR/Downloader/Package.php

To be consistent with PR #44 we also need to skip the check here.

skip check (in base) when packagingroot used (different tree)

---

PEAR/Downloader.php
PEAR/Proxy.php
PEAR/REST.php
package2.xml

At the moment, we handle proxy requests for HTTPS URLs (almost) the same
as regular non-encrypted HTTP requests. This means that we send a line
similar to this to the proxy:
GET https://pear.horde.org HTTP/1.1
Many proxies do not handle proxy requests when they contain a HTTPS URL
(for example, Squid) and fail e.g. with a 501 Not Implemented error.
The proper way to make these requests is through the CONNECT verb.
This not only solves the issues with proxies that do not handle the
aforementioned GET requests with HTTPS URLs, but also increses security,
as we can do the SSL certificate validation by ourselves and do not have
to trust the proxy.
Additionally, we no longer speak HTTPS with the proxy in case we request
a HTTPS URL as it is simply no longer needed.
This patch improves upon PR …

Add proper HTTPS proxy support through the CONNECT verb

---

PEAR/REST.php

http://pear.php.net/bugs/bug.php?id=21188

fix #21188 Class 'PEAR_Proxy' not found

---

PEAR/PackageFile/v2.php

```
$ pecl list-all
Warning: Invalid argument supplied for foreach() in PEAR/PackageFile/v2.php on line 1675
PHP Warning:  Invalid argument supplied for foreach() in /usr/share/pear/PEAR/PackageFile/v2.php on line 1675
All packages [Channel pecl.php.net]:
====================================
Package               Latest  Local
pecl/amfext           0.9.2                ActionScript Message Format extension
...
```
This happens when dep is a string (ie, "os" = "linux")

fix warning during pecl list-all

---

PEAR/Command/Install.php

https://pear.php.net/bugs/bug.php?id=18102
This calls `raiseError` in the event of a package error, which causes an error code (1) to be returned to the shell.
All tests still pass, but admittedly, I don't know enough about pear internals to know if this change would have adverse side effects. It does have the potential to catch some build processes that may be silently failing currently (my comment on #18102 describes the situation that we ran into with the "zip" pecl package silently failing during our docker image builds).

fix #18102 pear install does not fail on error

---

package2.xml

One less thing to do... package2.xml now recommends 1.4.3 of Archive_Tar; thought it best to not adjust the min value.

PHP 7.2: Up recommended version of Archive_Tar (in package xml file).

---

install-pear.php

Hello, when compiling PHP from source the following notice appears:
```
Notice: Undefined variable: metadata_dir in phar://install-pear-nozlib.phar/index.php on line 255
```
If I'm correct, this patch should fix this. In case I've missed something, let me know. Thanks for checking it out or considering merging it.

Fix notice undefined variable metadata_dir

---

System.php

e.g. a Windows '.bat' file may be reported as not executable by is_executable and still be usable...
This patch drops that check.

Bug #23744  Remove is_executable check in System::which 

---

PEAR/Downloader/Package.php

@ashnazg php 7.0 emits 
> Unable to find the wrapper "channel"
as channel URL if passed to file functions
PEAR Version: 1.10.6

Prevent Unable to find the wrapper "channel" Warning

---

scripts/pecl.sh

Hello,
when PHP is using shared extensions (this goes mainly for the xml and openssl) the php CLI command needs to enable those separately for each required extension that PEAR and PECL are using.
To illustrate this more simply:
When PHP is build with something like 
```bash
./configure --with-openssl=shared --enable-xml=shared
```
Then pecl CLI script won't work ok... This patch fixes this.

Add flags to PECL shell script for shared extensions

---

PEAR/RunTest.php

as this may raise E_DEPRECATED warning and thus make test suite fail
BTW, PEAR still heavily rely on deprecated php_errmsg (ini_set being protected by silent operator)
so a long term solution seems needed.

Drop track_errors from options,

---

PEAR/Builder.php
PEAR/Common.php
PEAR/Frontend.php
PEAR/PackageFile.php

Fixes issue during `pecl install`
```
Fatal error: Uncaught Error: Non-static method PEAR_Frontend::addTempFile() cannot be called statically in /usr/local/lib/php/PEAR/Common.php:213
Stack trace:
#0 /usr/local/lib/php/PEAR/Builder.php(279): PEAR_Common->addTempFile('/tmp/pear/temp/...')
#1 /usr/local/lib/php/PEAR/Installer.php(1519): PEAR_Builder->build('/tmp/pear/temp/...', Array)
#2 /usr/local/lib/php/PEAR/Installer.php(1415): PEAR_Installer->_compileSourceFiles('pecl.php.net', Object(PEAR_PackageFile_v2))
#3 /usr/local/lib/php/PEAR/Command/Install.php(713): PEAR_Installer->install('/tmp/pear/downl...', Array)
#4 /usr/local/lib/php/PEAR/Command/Common.php(270): PEAR_Command_Install->doInstall('install', Array, Array)
#5 /usr/local/lib/php/pearcmd.php(316): …
```

Fixes static calls for PHP 8

---

scripts/pearcmd.php

To account for https://github.com/php/php-src/commit/a302d1161036988fe220ecd8ecd73e6af1a116fc. Otherwise a whole flood of silenced warnings gets displayed :)

Adjust silencing check for PHP 8

---

PEAR/Builder.php

When having an @ in the php bin_dir (default for PHP installations on OSX with Homebrew), the preg_match fails. Dynamic values should be filtered by preg_quote to prevent issues like this.
Related to "Merge pull request pear#88 from remicollet/issue-75852"

Added missing preg quote

---

scripts/pearcmd.php
scripts/peclcmd.php

I was confused by why my PECL-specific changes didn't seem to be doing anything until I realised that `peclcmd.php` doesn't specify an absolute path for `pearcmd.php`, instead falling back to `include_path`. If PEAR is installed on the system the include_path will by default include `/usr/share/php`, resulting in us incorrectly(?) including the installed version rather than the "raw" one in the checkout.
I also noticed that only `.` appears in `include_path`, not specifically the root directory of the checkout. This means executing e.g. `../pear/scripts/pecl.sh build` from within a PECL extension directory will include the system PEAR files rather than the raw checkout.
From the commit log:
* The scripts/ directory itself should appear in include_path if we're
relying on it to source …

Fix scripts/* include paths

---

man1/pear.1

```shell
LC_ALL=en_US.UTF-8 MANROFFSEQ='' MANWIDTH=80 \
man --warnings -E UTF-8 -l -Tutf8 -Z man1/pear.1 > /dev/null
```
Outputs:
```
troff: <standard input>:230: warning: macro 'PS' not defined
```
We use "Example begin" (`.EX`)/"Example end" (`.EE`) instead, see [groff_man(7)](https://manpages.debian.org/unstable/groff/groff_man.7).

Fix manpage warning

---

PEAR.php
PEAR/Registry.php

See https://reproducible-builds.org/specs/source-date-epoch/
This is necessary to have reproducible builds.
Bug-Debian: https://bugs.debian.org/750697

Implement the SOURCE_DATE_EPOCH specification

---

OS/Guess.php

Also move the "simple" way first
to avoid file parsing or shell call
Notice: it seems that this information if not really used anywhere
and I'm not aware of any pear/pecl package with constraint on glibc version

handle "lib64" case for glibc detection

---

PEAR/Builder.php
PEAR/Command/Build.php
PEAR/Command/Build.xml
PEAR/Command/Install.php
PEAR/Command/Install.xml
PEAR/Downloader.php
PEAR/Installer.php
tests/PEAR_Command/test_registerCommands_standard.phpt

I'm currently working on automating installation of a PHP extension via PECL from within a configuration management tool, but extensions with mandatory `<configureoption>`s currently require answers interactively. This forces me to either spam `stdin` with a fixed set of inputs (flaky) or use `expect` (also flake).
These changes:
* Introduce new `--configureoptions` (`-D`) switch for `build` and `install` commands
* Add rudimentary configuration option parsing to `PEAR_Builder`
* Only prompt for user input if no value exists in the parsed options
* Patch up tests to accommodate new switch
I realise further changes might be necessary to get this mergeable:
1. Argument parsing is a bit gross (using an XML parser to resolve key-value pairs from a string of options... how else could I do …

Non-interactive <configureoption /> answers

---

.travis.yml

Alternatively we can remove them altogether.

Fix Travis builds on PHP 5.4 and 5.5

---

PEAR/Command/Remote.php
PEAR/DependencyDB.php

This fixes a number of notices that are thrown on PHP 7.4.

Fix use of null/false as array

---

OS/Guess.php
PEAR/Builder.php
PEAR/Command.php
PEAR/Command/Channels.php
PEAR/Command/Common.php
PEAR/Command/Config.php
PEAR/Common.php
PEAR/Config.php
PEAR/DependencyDB.php
PEAR/Downloader.php
PEAR/Installer.php
PEAR/Installer/Role.php
PEAR/PackageFile.php
PEAR/PackageFile/Generator/v1.php
PEAR/PackageFile/Generator/v2.php
PEAR/PackageFile/v1.php
PEAR/PackageFile/v2/Validator.php
PEAR/Registry.php
PEAR/Start.php
PEAR/Start/CLI.php
PEAR/Validate.php
System.php
make-gopear-phar.php
make-installpear-nozlib-phar.php
make-pear-bundle.php

Deprecated: Array and string offset access syntax with curly braces is deprecated
Hopefully these are all (or most) of them:
```
[Clover@Clover-NB pear-core](fix-deprecation-curly-braces)$ rg -tphp "(\\$|->|::)[A-Za-z0-9_]+\{"
make-gopear-phar.php:43:    if ($entry{0} == '.' || !in_array(substr($entry, -4), array('.tar'))) {
make-installpear-nozlib-phar.php:43:    if ($entry{0} == '.' || !in_array(substr($entry, -4), array('.tar'))) {
make-pear-bundle.php:34:                        $checksum += ord($hdr_data{$i});
make-pear-bundle.php:38:                        $checksum += ord($hdr_data{$i});
System.php:77:                if ($b{0} == '"' || $b{0} == "'") {
OS\Guess.php:256:                if ($line{0} == '#' || trim($line) == '') {
PEAR\Builder.php:194:            if ($ent{0} == '.') …
```

Fix PHP 7.4 deprecation: array/string curly braces access

---

README.CONTRIBUTING

Without the `--force` option we get an error:
```
Failed to download pear/php_archive within preferred state "stable", latest release is version 0.12.0, stability "alpha", use "channel://pear.php.net/php_archive-0.12.0" to install
install failed
```

Fix documentation: the `--force` is required

---

PEAR/REST.php

While fixing notice (which was actually fixed in #93 by @remicollet) noticed that logic in `useLocalCache` is duplicate with `getCacheId`
This PR aims to remove duplicate code.

Updated logic in useLocalCache to reuse getCacheId

---

PEAR/Builder.php

fix this  warning.
```
enable igbinary serializer support? [no] :
Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in PEAR/Builder.php on line 407
Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/lib/php/PEAR/Builder.php on line 407
enable lzf compression support? [no] :
Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in PEAR/Builder.php on line 407
Warning: Use of undefined constant name - assumed 'name' (this will throw an Error in a future version of PHP) in /usr/local/lib/php/PEAR/Builder.php on line 407
enable zstd compression support? [no] :
Warning: Use of undefined constant name - …
```

Fix undefined constant name

---

PEAR/REST.php

When a url is not in the cache, getCacheId will return 'false' but this is not caught before using cacheid['age'].
Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 181
PHP Notice: Trying to access array offset on value of type bool in /usr/share/php7/PEAR/PEAR/REST.php on line 181

Fix logging error for urls not in cache

---

PEAR/Registry.php

filesystem `readdir` order is non-deterministic
so the `.filemap` output was observed to have variations in ordering
across builds (in scratch VMs/FSes).
See https://reproducible-builds.org/ for why this matters.
Note: could not test this, because I could not get the
.phar file updated with this patch after an hour.
This patch was done while working on reproducible builds in openSUSE.

Sort list of packages

---

PEAR/REST.php

As pointed out by @arjendekorte, #106 should never have been merged, since #102 already provided a better fix.

Remove unneeded code

---

.travis.yml

Hi,
I had added ppc64le architecture to run travis ci  and looks like its been successfully added. I believe it is ready for the final review and merge. As there is no support for php 5.4 and 5.5 for the ppc64le architecture, hence jobs are excluded for the same. 
Please have a look.
Thanks!!"

Adding ppc64le architecutre to support travis-ci

---

PEAR/Downloader.php

This fixes a typo (an instead on a) and a possible solution.
maybe we can enhance the error output more somehow?

unsupported protocol - use --force to continue

---

OS/Guess.php

This PR has a minor fix for the `OS_Guess` class.
Calling `_determineIfPowerpc` without `$this` operator leads to the following error on `macOS`.
```bash
Fatal error: Uncaught Error: Call to undefined function _determineIfPowerpc()
```
Error: https://3v4l.org/sog9H

Add $this operator to _determineIfPowerpc calls

---

OS/Guess.php

This is supposed to be a method call, not a subtraction.

Fix PHP bug 81653: Typo in install-pear-nozlib.phar

---

PEAR.php

Discovered running Cache_Lite test suite, but may affects some others

Fix: Creation of dynamic property PEAR_Error::$callback is deprecated

---

PEAR/Installer.php

This check is used to make sure we don't overwrite binary files that are already in use, as doing so will cause a segmentation fault. This is reported among others in https://bugs.xdebug.org/view.php?id=2167, but I have ran into this in many occasions.
However, this check never worked, since its introduction 19 years ago, as the `return` was missing, and the suffix as created by `basename` does not include the `.`.

Fixed extension loaded check for pecl binaries

---

tests/PEAR_Command_Package/package/packagefiles/DB_Table/DB/Table/Generator.php

Fix deprecated style of passing arguments to `implode()` function for PHP 7.4+
https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.implode-reverse-parameters

Put glue and pieces parameters to implode in correct order for PHP 7.4+

---

PEAR/Proxy.php

$proxy_host, $proxy_port are only defined with $this reference.
A previous commit 250c425718c3d438222ce2d570d2241af6e709c1 partially fixed one such error.

eliminate undefined variable warnings on errors

---

scripts/pecl.bat

As described in f94454a74785865cec50bf9d64c410efc29b587a
> When PHP is using shared extensions:
>
> `./configure --with-openssl=shared --enable-xml=shared`
>
> The -n option in PHP command line (in the PECL shell script) removes them from being enabled and PECL script won't work ok anymore. This goes mainly for the xml and openssl PHP extensions which are needed to install PECL extensions via the https protocol and to parse XML files.
Unfortunately, the fix was only applied to `pecl.sh`, so the issue described in https://bugs.php.net/bug.php?id=77522 still occurs on Windows when built with shared extensions.
This PR applies the same fix to `pecl.bat` to avoid the issue on Windows.

Remove -n option from pecl.bat for shared extensions

---

PEAR/RunTest.php
make-gopear-phar.php
make-installpear-nozlib-phar.php
scripts/pearcmd.php
tests/PEAR_Error/pear_error.phpt

See https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
Close https://github.com/pear/pear-core/issues/144

Never reference E_STRICT on PHP 8.4+

---

PEAR/DependencyDB.php
PEAR/Registry.php

Fixes a bug introduced in commit 61ffb66 which triggers "array to string" conversion warnings on various actions

Fix bug #27796: "Array to string" conversion warnings on installs/other actions
